# Workflow name
name: Check my site

# Define when the workflow should run
on:
  schedule:
    - cron: '0 9 * * 6'  # Run weekly on Saturday at 09:00
  workflow_dispatch:  # Allow manual triggering

# Set permissions for the workflow
permissions:
  contents: write  # Add explicit permission to write to repository

jobs:
  check_links:
    runs-on: ubuntu-latest
    
    steps:
    # Check out the repository code
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Use Github token for authentication

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # Cache Node.js modules to speed up subsequent runs
    - name: Cache Node.js modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
    
    # Install the linkinator tool globally
    - name: Install dependencies
      run: npm install linkinator -g
    
    # Create a directory to store reports
    - name: Create reports directory
      run: mkdir -p reports
    
    # Run linkinator to check for broken links
    - name: Check for broken links
      run: |
        DATE=$(date +'%Y-%m-%d')
        REPORT_FILE="reports/ab_links_report_$DATE.csv"
        linkinator "${{ secrets.AB_URL }}" --recurse --skip "^(?:https?:\/\/(?:dx\.)?doi\.org|.*\.(png|jpg|jpeg|gif|svg|ico)$)"  --format CSV > $REPORT_FILE
        echo "REPORT_FILE=$REPORT_FILE" >> $GITHUB_ENV
      continue-on-error: true  # Continue even if linkinator finds errors
    
    # Check if any 404 broken links were found in the report
    - name: Check if broken links were found
      id: check_broken_links
      run: |
        if grep -qE '\b(404)\b' "${{ env.REPORT_FILE }}"; then
          echo "broken_links_found=true" >> $GITHUB_OUTPUT
          echo "STATUS_MESSAGE=Broken 404 links have been detected on the website. Please check attached report for all link details." >> $GITHUB_ENV
        else
          echo "broken_links_found=false" >> $GITHUB_OUTPUT
          echo "STATUS_MESSAGE=No 404 broken links found. Please check attached report for all link details." >> $GITHUB_ENV
        fi
    
    # Commit the report to the repository
    - name: Commit report to repository
      if: always()  # Run this step regardless of previous step outcomes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add "${{ env.REPORT_FILE }}"
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Add links report for $(date +'%Y-%m-%d')"
          git push origin HEAD:${GITHUB_REF}
        fi
        
    # Upload the report as an artifact
    - name: Upload links report
      if: always()  # Run this step regardless of previous step outcomes
      uses: actions/upload-artifact@v4
      with:
        name: links-report
        path: ${{ env.REPORT_FILE }}
    
    # Send an email notification with the report
    - name: Send email notification
      id: send_email
      if: always()  # Run this step regardless of previous step outcomes
      uses: dawidd6/action-send-mail@v3
      with:
        # Email server settings
        server_address: smtp.gmail.com
        server_port: 465
        # Credentials for the email account
        username: ${{secrets.GMAIL_USERNAME}}
        password: ${{secrets.GMAIL_PASSWORD}}
        # Email subject (changes based on whether broken links were found)
        subject: ${{ steps.check_broken_links.outputs.broken_links_found == 'true' && 'Broken 404 Links Found on your website' || 'No 404 Broken Links Found on your website' }}
        body: ${{ env.STATUS_MESSAGE }}
        attachments: ${{ env.REPORT_FILE }}
        # Recipient and sender email addresses
        to: ${{secrets.EMAIL_RECIPIENT}}
        from: Library Linkchecker ${{secrets.EMAIL_SENDER}}
        priority: normal
        secure: true  # Use TLS for the email connection
      env:
        STATUS_MESSAGE: ${{ env.STATUS_MESSAGE }}
